Problem: nightly cargo fmt complains
```
error[internal]: left behind trailing whitespace
Error:   --> /home/runner/work/bpxe/bpxe/tests/bpmn_test.rs:20:20:48
   |
20 |     assert!(matches!(&flow.condition_expression,
   |
```

Solution: fix the trailing whitespace there

I didn't see this because I don't run nightly cargo fmt locally.