Problem: syn 1.0.60 broke builds
In CI, where a newer version of `syn` crate was pulled, got this error:

```
error[E0599]: no variant or associated item named `__Nonexhaustive` found for enum `syn::Type` in the current scope
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tia-1.0.0/src/detail/parser/stringify.rs:87:14
   |
87 |   syn::Type::__Nonexhaustive => panic!("tia not implemented feature: __Nonexhaustive, please write PR or Issue if you want the feature. #...
   |              ^^^^^^^^^^^^^^^
   |              |
   |              variant or associated item not found in `syn::Type`
   |              help: there is a variant with a similar name: `__TestExhaustive`
 ```

Solution: don't upgrade to 1.0.60 yet, stay on .59

I've sent an upgrade PR to Tia: https://github.com/usagi/tia/pull/3, so
once that is successfully resolved, the restriction can be relaxed.