Problem: sample BPMN file used for testing doesn't declare xsi ns
I noticed it doesn't have xmlns:xsi attribute at the root and the XML
parsing test error looks like this:

```
-- parse_sample stdout ----
thread 'parse_sample' panicked at 'called `Result::unwrap()` on an `Err`
value: NormalizationError { error: ParsingError { error: Error {
location: 1134, errors: {UnknownNamespacePrefix} } } }',
```

Solution: declare it

Now the error looks like this:

```
---- parse_sample stdout ----
thread 'parse_sample' panicked at 'called `Result::unwrap()` on an `Err`
value: ParsingError { error: UnexpectedToken { token: "Ok(Text { text:
StrSpan(\"\\n    \" 1063..1068) })" } }', tests/bpmn_test.rs:8:49 note:
```

(which is how it is reported in #1)