Problem: uploading master docs failed
Error:

```
CommandException: "rsync" command does not support provider-only URLs.
```

Solution: use google-github-actions/upload-cloud-storage@main
for clarity and hope that it will work fine this time