Problem: failing deprecation notice lint
cargo clippy fails with:

```
error: use of deprecated associated function `streamunordered::StreamUnordered::<S>::push`: Prefer StreamUnordered::insert
   --> bpxe/src/activity/mod.rs:152:46
    |
152 |             flow_node_tokens.push(flow_nodes.push(activity));
    |                                              ^^^^
    |
    = note: `-D deprecated` implied by `-D warnings`
```

Solution: use the new API

The change was introduced here https://github.com/jonhoo/streamunordered/commit/cd203a48c3cd566b34840d16a6ab439ac618da73